const SITE = {
  unit: "إمكانية الاتصال والشبكات",
  grade: "",
};

/** التسلسل التعليمي من إمكانية الاتصال حتى التقنيات الناشئة */
const PATH = [
  { id: "connect", group: "connect", label: "ما هي إمكانية الاتصال؟", short: "التعريف", nav: "connect" },
  { id: "wired", group: "connect", label: "الطرق السلكية", short: "سلكي", nav: "connect" },
  { id: "wireless", group: "connect", label: "الطرق اللاسلكية", short: "لاسلكي", nav: "connect" },
  { id: "needs", group: "connect", label: "الاحتياجات والآثار والأداء", short: "قرار الاتصال", nav: "connect" },
  { id: "networks", group: "networks", label: "أنواع الشبكات", short: "أنواع الشبكات", nav: "networks" },
  { id: "factors", group: "networks", label: "عوامل اختيار الشبكة", short: "عوامل الاختيار", nav: "networks" },
  { id: "parts", group: "networks", label: "مكونات الشبكة", short: "المكونات", nav: "networks" },
  { id: "protocols", group: "tx", label: "البروتوكولات", short: "البروتوكولات", nav: "tx" },
  { id: "tx", group: "tx", label: "أمن النقل والنطاق الترددي", short: "أمن وسرعة", nav: "tx" },
  { id: "compress", group: "tx", label: "الضغط وبرامج الترميز", short: "ضغط وترميز", nav: "tx" },
  { id: "online", group: "online", label: "التخزين والحوسبة السحابية", short: "السحابة", nav: "online" },
  { id: "remote", group: "online", label: "العمل عن بُعد", short: "عن بُعد", nav: "online" },
  { id: "online-choose", group: "online", label: "اختيار الأنظمة عبر الإنترنت", short: "اختيار أونلاين", nav: "online" },
  { id: "emerging", group: "emerging", label: "التقنيات الناشئة", short: "ناشئة", nav: "emerging" },
];

const GROUPS = {
  connect: PATH.filter((p) => p.group === "connect"),
  networks: PATH.filter((p) => p.group === "networks"),
  tx: PATH.filter((p) => p.group === "tx"),
  online: PATH.filter((p) => p.group === "online"),
  emerging: PATH.filter((p) => p.group === "emerging"),
};

/** مصطلحات إنجليزية مع النطق والمعنى. say = ما يُلفَظ عند الضغط على السماعة */
const GLOSSARY = [
  { en: "connectivity", full: "Connectivity", ar: "إمكانية الاتصال: معالجة البيانات الرقمية بتوصيل نظام التشغيل بالتطبيقات والأنظمة وببعضها", say: "connectivity", group: "اتصال" },
  { en: "bandwidth", full: "Bandwidth", ar: "النطاق الترددي: المقدار المتاح من قدرة نقل البيانات", say: "bandwidth", group: "اتصال" },
  { en: "latency", full: "Latency", ar: "زمن الاستجابة / التأخير", say: "latency", group: "نقل" },
  { en: "wired", full: "Wired connection", ar: "اتصال سلكي دائم بالكابلات المخصصة", say: "wired", group: "اتصال" },
  { en: "wireless", full: "Wireless", ar: "لاسلكي: اتصال بلا أسلاك", say: "wireless", group: "اتصال" },
  { en: "peripheral", full: "Peripheral device", ar: "جهاز طرفي (طابعة، لوحة مفاتيح، شاشة…)", say: "peripheral", group: "اتصال" },
  { en: "sync", full: "Synchronisation", ar: "مزامنة البيانات بين الأجهزة", say: "sync", group: "اتصال" },
  { en: "health and safety", full: "Health and safety", ar: "الصحة والسلامة (مثل خطر الكابلات المتناثرة)", say: "health and safety", group: "اتصال" },
  { en: "USB", full: "Universal Serial Bus", ar: "ناقل تسلسلي عام: ثنائي الاتجاه، حتى 127 جهازًا، وقد يُغذّي الجهاز بالطاقة", say: "U S B, Universal Serial Bus", group: "اتصال" },
  { en: "Ethernet", full: "Ethernet", ar: "إيثرنت: نظام لتوصيل حواسيب لتشكيل شبكة محلية", say: "Ethernet", group: "اتصال" },
  { en: "fibre optic", full: "Fibre optic / Optical fibre", ar: "ألياف ضوئية: خيوط زجاج سيليكا تنقل البيانات بالضوء بسرعة ونطاق أعلى ولمسافات أطول", say: "fibre optic", group: "اتصال" },
  { en: "HDMI", full: "High-Definition Multimedia Interface", ar: "واجهة وسائط متعددة عالية الدقة: موصل رقمي للصوت والصورة", say: "H D M I, High-Definition Multimedia Interface", group: "اتصال" },
  { en: "DVI", full: "Digital Visual Interface", ar: "واجهة بصرية رقمية: موصل رقمي للشاشات", say: "D V I, Digital Visual Interface", group: "اتصال" },
  { en: "Bluetooth", full: "Bluetooth", ar: "بلوتوث: لاسلكي قصير المدى (حوالي 100 م) للفأرة والسماعات ولوحة المفاتيح", say: "Bluetooth", group: "اتصال" },
  { en: "Wi-Fi", full: "Wi-Fi / Wireless Fidelity", ar: "واي فاي: شبكة لاسلكية محلية للاتصال بالإنترنت أو بالمؤسسة", say: "Wi-Fi", group: "اتصال" },
  { en: "NFC", full: "Near Field Communication", ar: "اتصال قريب المدى: جهازان يتصلان من مسافة قريبة جدًا", say: "N F C, Near Field Communication", group: "اتصال" },
  { en: "IR", full: "Infrared", ar: "أشعة تحت حمراء: مثل أجهزة التحكم عن بُعد للتلفزيون", say: "infrared", group: "اتصال" },
  { en: "cellular", full: "Cellular / mobile network", ar: "شبكة خلوية/محمولة: تُقسَم الأرض إلى خلايا لكل منها محطة إرسال", say: "cellular network", group: "اتصال" },
  { en: "3G", full: "Third Generation", ar: "الجيل الثالث من شبكات الهاتف المحمول", say: "three G", group: "اتصال" },
  { en: "4G", full: "Fourth Generation", ar: "الجيل الرابع: تطبيقات متعددة وتجربة أسرع على الجوال", say: "four G", group: "اتصال" },
  { en: "5G", full: "Fifth Generation", ar: "الجيل الخامس: أسرع وأكثر استقرارًا وأمانًا، وزمن انتقال منخفض جدًا", say: "five G", group: "ناشئة" },
  { en: "tethering", full: "Tethering", ar: "توسعة الوصول: مشاركة إنترنت الهاتف مع جهاز آخر", say: "tethering", group: "اتصال" },
  { en: "AirDrop", full: "AirDrop", ar: "إير دروب: مشاركة ملفات قريبة على أجهزة Apple عبر NFC/لاسلكي", say: "AirDrop", group: "اتصال" },
  { en: "EMI", full: "Electromagnetic interference", ar: "تداخل كهرومغناطيسي قد يفسد الكابلات النحاسية", say: "electromagnetic interference", group: "اتصال" },
  { en: "PAN", full: "Personal Area Network", ar: "الشبكة الشخصية: أجهزة الفرد (هاتف، لابتوب، طابعة، سيارة)", say: "P A N, Personal Area Network", group: "شبكات" },
  { en: "LAN", full: "Local Area Network", ar: "شبكة المنطقة المحلية: داخل مبنى أو منطقة صغيرة، والمؤسسة تملك الروابط", say: "L A N, Local Area Network", group: "شبكات" },
  { en: "WAN", full: "Wide Area Network", ar: "شبكة المنطقة الواسعة: أوسع من LAN وقد تصل عالميًا، والبنية غالبًا لمزوّد اتصالات", say: "W A N, Wide Area Network", group: "شبكات" },
  { en: "VPN", full: "Virtual Private Network", ar: "الشبكة الظاهرية الخاصة: نفق آمن عبر الإنترنت للأجهزة البعيدة", say: "V P N, Virtual Private Network", group: "شبكات" },
  { en: "Internet", full: "Internet", ar: "الإنترنت: مجموعة من شبكات WAN العالمية", say: "Internet", group: "شبكات" },
  { en: "intranet", full: "Intranet", ar: "إنترانت: موقع/شبكة داخلية للمستخدمين الداخليين فقط", say: "intranet", group: "شبكات" },
  { en: "extranet", full: "Extranet", ar: "إكسترانت: إنترانت يُسمح لمستخدمين خارجيين مصرّح لهم بالوصول إليها", say: "extranet", group: "شبكات" },
  { en: "router", full: "Router", ar: "جهاز التوجيه: يربط الشبكات بالإنترنت (واي فاي أو نطاق عريض)", say: "router", group: "شبكات" },
  { en: "switch", full: "Switch", ar: "المحوّل: واجهة بين إرسال البيانات واستقبالها داخل الشبكة", say: "switch", group: "شبكات" },
  { en: "WAP", full: "Wireless Access Point", ar: "نقطة وصول لاسلكية: توصل أجهزة الواي فاي بشبكة سلكية", say: "W A P, wireless access point", group: "شبكات" },
  { en: "protocol", full: "Protocol", ar: "بروتوكول: مجموعة قواعد تحكم بدء الإرسال وتشفير البيانات وإنهاءه", say: "protocol", group: "نقل" },
  { en: "HTTP", full: "Hypertext Transfer Protocol", ar: "بروتوكول نقل النص التشعبي لصفحات الويب", say: "H T T P, Hypertext Transfer Protocol", group: "نقل" },
  { en: "HTTPS", full: "Hypertext Transfer Protocol Secure", ar: "إصدار آمن من HTTP يستخدم SSL/TLS لتشفير البيانات الحساسة", say: "H T T P S, Hypertext Transfer Protocol Secure", group: "نقل" },
  { en: "SSL", full: "Secure Sockets Layer", ar: "طبقة المقابس الآمنة (تشفير قديم نسبيًا)", say: "S S L, Secure Sockets Layer", group: "نقل" },
  { en: "TLS", full: "Transport Layer Security", ar: "أمان طبقة النقل: تشفير المفتاح العام لنقل آمن", say: "T L S, Transport Layer Security", group: "نقل" },
  { en: "POP3", full: "Post Office Protocol version 3", ar: "بروتوكول مكتب البريد 3: يسترجع البريد من الخادم (غالبًا يُنزَّل)", say: "P O P 3, Post Office Protocol", group: "نقل" },
  { en: "IMAP4", full: "Internet Message Access Protocol version 4", ar: "بروتوكول الوصول إلى رسائل الإنترنت 4: يصل للبريد على الخادم دون إزالته", say: "I M A P 4, Internet Message Access Protocol", group: "نقل" },
  { en: "SMTP", full: "Simple Mail Transfer Protocol", ar: "بروتوكول نقل البريد البسيط: لإرسال البريد إلى الخادم", say: "S M T P, Simple Mail Transfer Protocol", group: "نقل" },
  { en: "FTP", full: "File Transfer Protocol", ar: "بروتوكول نقل الملفات: رفع وتنزيل ملفات من خادم", say: "F T P, File Transfer Protocol", group: "نقل" },
  { en: "VoIP", full: "Voice over Internet Protocol", ar: "نقل الصوت عبر بروتوكول الإنترنت بدل خط الهاتف", say: "V o I P, Voice over Internet Protocol", group: "نقل" },
  { en: "TCP/IP", full: "Transmission Control Protocol / Internet Protocol", ar: "IP للعنوان، وTCP لتنظيم النقل الآمن وتكامل البيانات", say: "T C P I P, Transmission Control Protocol and Internet Protocol", group: "نقل" },
  { en: "SIP", full: "Session Initiation Protocol", ar: "بروتوكول بدء الجلسة لمكالمات VoIP", say: "S I P, Session Initiation Protocol", group: "نقل" },
  { en: "RTP", full: "Real-time Transport Protocol", ar: "بروتوكول النقل في الوقت الفعلي للصوت/الفيديو", say: "R T P, Real-time Transport Protocol", group: "نقل" },
  { en: "ping", full: "Ping test", ar: "اختبار البينغ: زمن ذهاب حزمة ICMP وعودتها بالمللي ثانية", say: "ping", group: "نقل" },
  { en: "Mbps", full: "Megabits per second", ar: "ميغا بت في الثانية: وحدة قياس سرعة النقل", say: "megabits per second", group: "نقل" },
  { en: "encryption", full: "Encryption", ar: "التشفير: تحويل البيانات إلى كود يمنع الوصول غير المصرّح", say: "encryption", group: "نقل" },
  { en: "PGP", full: "Pretty Good Privacy", ar: "خصوصية جيدة جدًا: أدوات تشفير سهلة الوصول", say: "P G P, Pretty Good Privacy", group: "نقل" },
  { en: "lossy", full: "Lossy compression", ar: "ضغط بفاقد: يُزيل بيانات فتصغر الملفات وتنخفض الجودة", say: "lossy compression", group: "نقل" },
  { en: "lossless", full: "Lossless compression", ar: "ضغط بلا فاقد: يصغّر الملف ويمكن استعادة الأصل كاملًا", say: "lossless compression", group: "نقل" },
  { en: "codec", full: "Codec", ar: "برنامج/جهاز ترميز: يضغط أو يرمّز تدفق الصوت والفيديو", say: "codec", group: "نقل" },
  { en: "JPEG", full: "Joint Photographic Experts Group", ar: "تنسيق صور بفاقد", say: "J PEG", group: "نقل" },
  { en: "MP3", full: "MPEG Audio Layer 3", ar: "صوت بفاقد: يزيل أصواتًا شبه غير مسموعة", say: "M P 3", group: "نقل" },
  { en: "MP4", full: "MPEG-4", ar: "حاوية لملفات صوت وفيديو وصور ونصوص، غالبًا بفاقد", say: "M P 4", group: "نقل" },
  { en: "PNG", full: "Portable Network Graphics", ar: "صور بلا فاقد", say: "P N G", group: "نقل" },
  { en: "GIF", full: "Graphics Interchange Format", ar: "رسوم بلا فاقد (ألوان محدودة)", say: "G I F", group: "نقل" },
  { en: "FLAC", full: "Free Lossless Audio Codec", ar: "ترميز صوت رقمي بلا فاقد", say: "flac", group: "نقل" },
  { en: "ZIP", full: "ZIP archive", ar: "أرشيف مضغوط بلا فاقد للملفات", say: "zip", group: "نقل" },
  { en: "bit", full: "Bit", ar: "بِت: أصغر وحدة بيانات، 0 أو 1", say: "bit", group: "نقل" },
  { en: "cloud storage", full: "Cloud storage", ar: "تخزين سحابي: ملفات على خوادم مرتبطة تُوصَل عبر الإنترنت", say: "cloud storage", group: "سحابة" },
  { en: "cloud computing", full: "Cloud computing", ar: "حوسبة سحابية: برامج وموارد عند الطلب عبر خادم افتراضي", say: "cloud computing", group: "سحابة" },
  { en: "remote desktop", full: "Remote desktop", ar: "سطح المكتب البعيد: التحكم بجهاز من مكان آخر", say: "remote desktop", group: "سحابة" },
  { en: "URL", full: "Uniform Resource Locator", ar: "محدد موقع الموارد: عنوان صفحة الويب", say: "U R L, Uniform Resource Locator", group: "سحابة" },
  { en: "ADSL", full: "Asymmetric Digital Subscriber Line", ar: "خط اشتراك رقمي غير متناظر عبر خط الهاتف", say: "A D S L", group: "سحابة" },
  { en: "FTTC", full: "Fibre to the Cabinet", ar: "ألياف حتى الصندوق ثم نحاس للمنزل", say: "fibre to the cabinet", group: "سحابة" },
  { en: "FTTP", full: "Fibre to the Premises", ar: "ألياف حتى المبنى/المنزل", say: "fibre to the premises", group: "سحابة" },
  { en: "IoT", full: "Internet of Things", ar: "إنترنت الأشياء: ربط أجهزة الحوسبة (منزل ذكي، سيارات…)", say: "I o T, Internet of Things", group: "ناشئة" },
  { en: "virtualisation", full: "Virtualisation", ar: "المحاكاة الافتراضية: نسخة افتراضية من جهاز أو مورد", say: "virtualisation", group: "ناشئة" },
  { en: "containerisation", full: "Containerisation", ar: "النقل بالحاويات: عزل تطبيقات تستخدم نظام تشغيل المضيف", say: "containerisation", group: "ناشئة" },
  { en: "AR", full: "Augmented Reality", ar: "الواقع المعزز: صورة حاسوبية فوق العالم الحقيقي", say: "A R, Augmented Reality", group: "ناشئة" },
  { en: "VR", full: "Virtual Reality", ar: "الواقع الافتراضي: انغماس في عالم أنشأه الحاسوب", say: "V R, Virtual Reality", group: "ناشئة" },
  { en: "ML", full: "Machine Learning", ar: "التعلم الآلي: خوارزميات تتعلم من بيانات بلا تعليمات صريحة لكل خطوة", say: "M L, Machine Learning", group: "ناشئة" },
  { en: "AI", full: "Artificial Intelligence", ar: "الذكاء الاصطناعي: أنظمة تنفّذ مهامًا ذكية (تشخيص، تعرّف كلام…)", say: "A I, Artificial Intelligence", group: "ناشئة" },
  { en: "CPU", full: "Central Processing Unit", ar: "وحدة المعالجة المركزية: «دماغ» الحاسوب", say: "C P U, Central Processing Unit", group: "شبكات" },
  { en: "downtime", full: "Downtime", ar: "وقت التعطل: مدة توقف الأجهزة أو الشبكة", say: "downtime", group: "شبكات" },
  { en: "early adopter", full: "Early adopter", ar: "المتبني المبكر: من يسارع لشراء أحدث تقنية فور توفرها", say: "early adopter", group: "ناشئة" },
  { en: "stakeholder", full: "Stakeholder", ar: "صاحب مصلحة", say: "stakeholder", group: "ناشئة" },
];

const SCENARIOS = [
  {
    id: "warehouse",
    title: "مخزن طلبات",
    img: "img/warehouse-wifi.png",
    brief: "موظفون يتنقلون باستمرار لاختيار المخزون وجمع الطلبات على أجهزة محمولة.",
    q: "أي نوع اتصال أنسب هنا؟",
    options: [
      { t: "كابلات إيثرنت لكل عربة", d: "ثابتة وموثوقة جدًا", rank: "bad", why: "العامل يتحرك بلا مقر ثابت. الكابل يقيّده ويعطّل الإنتاجية. Wi-Fi أنسب داخل المخزن." },
      { t: "شبكة Wi-Fi داخل المخزن", d: "تنقّل حر مع ارتباط بالخادم", rank: "good", why: "التنقل المستمر يناسب الاتصال اللاسلكي. راقب التغطية في الزوايا المعدنية." },
      { t: "ألياف ضوئية لكل مكتب فقط", d: "أسرع نقل ممكن", rank: "ok", why: "الألياف ممتازة للمكتب الخلفي والخوادم، لكن ليست حل التنقل في الممرات. اجمع: ألياف للعمود الفقري + Wi-Fi للأرض." },
    ],
  },
  {
    id: "hospital",
    title: "سجلات بجانب سرير المريض",
    img: "img/hospital-tablet.png",
    brief: "ممرضون يحدّثون السجلات الطبية على أجهزة لوحية بجانب الأسرة. البيانات شخصية وحساسة.",
    q: "ما القرار الأذكى؟",
    options: [
      { t: "واي فاي مفتوح للسرعة", d: "أسهل للطاقم", rank: "bad", why: "السهولة لا تهزم الأمان هنا. البيانات الشخصية الحساسة تتطلب تشفيرًا وسياسات وصول." },
      { t: "لاسلكي مشفّر + سياسات وصول صارمة", d: "تنقّل مع حماية", rank: "good", why: "اللاسلكي مناسب بجانب السرير، لكن مع تشفير، كلمات مرور غير مشتركة، وجدار حماية. السرعة بلا أمان خسارة للمؤسسة." },
      { t: "حاسوب مكتبي سلكي في كل غرفة فقط", d: "كابل = أأمن دائمًا", rank: "ok", why: "السلكي أأمن نسبيًا، لكنه يبطئ التحديث عند السرير. يمكن أن يكون مكمّلًا للمحطات الثابتة، لا بديلًا كاملًا للتنقّل." },
    ],
  },
  {
    id: "studio",
    title: "استوديو إعلانات وفيديو",
    img: "img/studio-fibre.png",
    brief: "فريق يحرّر فيديو وصورًا عالية الدقة، ويحتاج أقصى سرعة لنقل ملفات ضخمة.",
    q: "أي بنية تحتية تختار؟",
    options: [
      { t: "واي فاي منزلي رخيص", d: "يوفر على الميزانية", rank: "bad", why: "الملفات الثقيلة + زمن الاستجابة = تأخير إنتاج. العمل عالي الدقة يحتاج أليافًا إلى الحواسيب المكتبية." },
      { t: "ألياف ضوئية إلى أجهزة التحرير", d: "أقصى سرعة وثبات", rank: "good", why: "الألياف تعطي نطاقًا أعلى ومسافة أطول، وتقلل التأخير عند نقل مشاريع الفيديو." },
      { t: "نحاس إيثرنت فقط", d: "وسط بين السرعة والتكلفة", rank: "ok", why: "معظم الشركات تكتفي بالنحاس كحل وسط. للاستوديو قد يكفي أحيانًا، لكن العمل عالي الدقة يبرر تكلفة الألياف." },
    ],
  },
  {
    id: "emi",
    title: "مصنع بتداخل كهرومغناطيسي",
    img: "img/wired-cables.png",
    brief: "آلات ثقيلة تولّد تداخلًا كهرومغناطيسيًا عاليًا. الكابلات النحاسية تفقد بيانات ويتدهور أداء الشبكة.",
    q: "ماذا تفعل؟",
    options: [
      { t: "زيادة عدد مقوّيات الواي فاي", d: "تجاوز الكابلات", rank: "bad", why: "التداخل اللاسلكي قد يسوء أيضًا في بيئة صناعية. المشكلة هنا في النحاس تحديدًا." },
      { t: "استبدال النحاس بألياف ضوئية", d: "الضوء لا يتأثر كالكهرباء", rank: "good", why: "عند التداخل الكهرومغناطيسي تصبح تكلفة الألياف ضرورية لمنع فقدان البيانات وتدهور الأداء." },
      { t: "الإبقاء على النحاس وتقصير الكابلات فقط", d: "توفير", rank: "ok", why: "التقصير يقلل بعض الضياع، لكنه لا يحل التداخل. قرار مؤقت لا يناسب أنظمة حرجة." },
    ],
  },
  {
    id: "remote",
    title: "شركة موظفوها موزَّعون",
    img: "img/remote-vpn.png",
    brief: "موظفون في مدن ودول مختلفة يحتاجون ملفات المكتب بأمان، وبعضهم يتعاون على مستندات في الوقت نفسه.",
    q: "أي مزيج أنسب؟",
    options: [
      { t: "VPN فقط لكل شيء", d: "نفق آمن للمكتب", rank: "ok", why: "VPN ممتاز للوصول إلى ملفات المكتب كأنك داخل LAN. لا يقدّم تعاون الوقت الحقيقي الذي تعطيه الحوسبة السحابية." },
      { t: "حوسبة سحابية فقط بدون حماية", d: "تعاون سهل", rank: "bad", why: "التعاون مهم، لكن الملفات الحساسة عبر إنترنت عام بلا نفق/سياسات = خطر. الأمان عامل اختيار أول." },
      { t: "VPN للوصول الداخلي + سحابة للتعاون", d: "أمن + إنتاجية", rank: "good", why: "موظف تكنولوجيا المعلومات يجمع الأداتين: VPN يضع البعيد داخل LAN المشفّرة، والسحابة للتحرير المشترك. هذا يطابق احتياجات الاستخدام لا «تقنية واحدة لكل شيء»." },
    ],
  },
  {
    id: "police",
    title: "جهة أمنية / شرطة",
    img: "img/hero-it-officer.png",
    brief: "بيانات حساسة جدًا، ويُفضَّل أن تبقى الأنظمة قائمة بذاتها وأأمن من السحابة العامة.",
    q: "أي نوع شبكة يناسب هنا؟",
    options: [
      { t: "تخزين سحابي عام مجاني", d: "رخيص ومتاح", rank: "bad", why: "WAN تتفوق هنا لأنها مستقلة ويمكن جعلها أأمن، ولهذا تستخدمها منظمات مثل قوات الشرطة." },
      { t: "WAN خاصة باشتراك اتصالات", d: "واسعة ومستقلة", rank: "good", why: "WAN أوسع من LAN، والمؤسسة لا تملك البنية عادة بل تدفع لمزوّد، لكنها تبقى قائمة بذاتها وأأمن من السحابة العامة في هذا السياق." },
      { t: "PAN بين هواتف الضباط فقط", d: "شخصية وبسيطة", rank: "ok", why: "PAN مفيدة لمزامنة جهاز شخصي، لكنها ليست شبكة المؤسسة عبر المدن." },
    ],
  },
];

const QUIZ = [
  {
    q: "إمكانية الاتصال Connectivity تعني:",
    opts: [
      "شراء أسرع راوتر في السوق فقط",
      "معالجة البيانات الرقمية بتوصيل نظام التشغيل بالتطبيقات والأنظمة وببعضها",
      "إرسال إيميل عبر SMTP",
      "ضغط الملفات بصيغة ZIP",
    ],
    correct: 1,
    why: "إمكانية الاتصال: القدرة على معالجة البيانات الرقمية من خلال توصيل نظام التشغيل بالتطبيقات والأنظمة ومع بعضها.",
  },
  {
    q: "ميزة كبيرة لـ USB؟",
    opts: [
      "يعمل بالضوء عبر مسافات قارية",
      "ثنائي الاتجاه وقد يزوّد الطرفيات بالطاقة ويخدم حتى 127 جهازًا",
      "مداه حوالي 100 متر بلا كابل",
      "هو بروتوكول بريد",
    ],
    correct: 1,
    why: "USB ناقل ثنائي الاتجاه، منفذ واحد حتى 127 جهازًا، ومن أكبر مميزاته تغذية الأجهزة الطرفية بالطاقة.",
  },
  {
    q: "الفرق الأهم بين POP3 و IMAP4؟",
    opts: [
      "POP3 للفيديو وIMAP4 للصوت",
      "IMAP4 يُستخدم لإرسال البريد فقط",
      "POP3 يسترجع البريد (غالبًا ينزّله)، وIMAP4 يصل إليه على الخادم دون إزالته",
      "لا يوجد فرق",
    ],
    correct: 2,
    why: "IMAP4 يصل إلى البريد على الخادم دون إزالته، بينما POP3 يسترده إلى العميل (غالبًا بالتنزيل).",
  },
  {
    q: "لماذا قد تختار مؤسسة أليافًا بدل النحاس رغم التكلفة؟",
    opts: [
      "لأن الألياف أرخص دائمًا",
      "نطاق أعلى، مسافة أطول، ومقاومة للتداخل الكهرومغناطيسي",
      "لأن HDMI لا يعمل إلا مع الألياف",
      "لأن البلوتوث لا يدعم الصوت",
    ],
    correct: 1,
    why: "الألياف تنقل بالضوء: نطاق ومسافة أعلى، وضرورية عند EMI حتى لا تُفقد البيانات.",
  },
  {
    q: "أي عبارة صحيحة عن VPN؟",
    opts: [
      "الخوادم التي تتصل بها سحابية وليست مادية",
      "تنشئ نفقًا افتراضيًا آمنًا عبر الإنترنت لتبدو بعيدًا كأنك داخل LAN",
      "تغني دائمًا عن التشفير",
      "هي نفسها الحوسبة السحابية",
    ],
    correct: 1,
    why: "VPN تستخدم الإنترنت لتوصيل أجهزة بعيدة بأمان. خوادمها مادية وليست سحابة، ولا تعطي تعاون التحرير اللحظي نفسه.",
  },
  {
    q: "JPEG و MP3 مثال على:",
    opts: [
      "ضغط بلا فاقد Lossless",
      "ضغط بفاقد Lossy",
      "بروتوكول بريد",
      "نوع شبكة PAN",
    ],
    correct: 1,
    why: "الضغط بفاقد يزيل بيانات (مثل أصوات شبه غير مسموعة في MP3) فيصغر الملف وتنخفض الجودة.",
  },
  {
    q: "HTTPS أهم من HTTP عندما:",
    opts: [
      "تتصفح خبرًا عامًا فقط",
      "تنقل بيانات حساسة مثل الخدمات المصرفية",
      "تستخدم بلوتوث للسماعات",
      "تضغط ملف ZIP",
    ],
    correct: 1,
    why: "HTTPS إصدار آمن يستخدم SSL/TLS وتشفير المفتاح العام. حرف s في https يعني secure، والقفل في المتصفح إشارة لذلك.",
  },
  {
    q: "زمن استجابة Latency مرتفع يؤثر خصوصًا في:",
    opts: [
      "حفظ ملف Word محلي فقط",
      "الألعاب عبر الإنترنت والأنظمة اللحظية مثل مراقبة جوية",
      "اختيار لون الشاشة",
      "عدد منافذ USB",
    ],
    correct: 1,
    why: "زمن الاستجابة العالي يجعل حركة اللعبة تظهر متأخرة، وقد يكلّف أنظمة الوقت الحقيقي (كالطيران) كارثة.",
  },
  {
    q: "التخزين السحابي Cloud storage يختلف عن الحوسبة السحابية Cloud computing في أن:",
    opts: [
      "الأول ملفات على خوادم، والثاني برامج وموارد عند الطلب",
      "لا فرق أبدًا",
      "الأول يحتاج كابل HDMI",
      "الثاني لا يحتاج إنترنت",
    ],
    correct: 0,
    why: "التخزين = مساحة ملفات ومشاركة. الحوسبة = تشغيل تطبيقات ومعالجة عبر الخادم الافتراضي (مستندات جوجل، Azure، AWS).",
  },
  {
    q: "نقطة الوصول اللاسلكية WAP:",
    opts: [
      "تحوّل الضوء إلى كهرباء في الألياف",
      "توصل أجهزة الواي فاي بشبكة سلكية، وتتأثر بعدد المستخدمين والطقس والترددات",
      "هي بروتوكول إرسال بريد",
      "تعني شبكة شخصية فقط",
    ],
    correct: 1,
    why: "WAP جسر بين اللاسلكي والسلكي. الأداء ليس ثابتًا: مستخدمون، تنزيلات، طقس، ترددات لاسلكية.",
  },
];
